FROM ubi8
USER root
COPY stress-ng/cmd.sh /root
COPY common-libs /root/common-libs
RUN yum -y install https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/stress-ng-0.14.00-1.el8.x86_64.rpm \
    && yum clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
