FROM fedora:39
USER root
COPY cyclictest/cmd.sh /root
COPY common-libs /root/common-libs
RUN yum -y install realtime-tests tmux stress-ng kernel-tools dumb-init \
    && yum clean all && rm -rf /var/cache/yum \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/root/cmd.sh"]
