# Using fedora to get a recent version of the rtla package
FROM fedora:39
USER root
COPY rtla/cmd.sh /root
COPY common-libs /root/common-libs
RUN yum -y install rtla dumb-init \
    && yum clean all && rm -rf /var/cache/yum \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/root/cmd.sh"]
