apiVersion: v1 
kind: Pod 
metadata:
  name: cyclictest 
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-custom-class
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    imagePullPolicy: IfNotPresent
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "4"
      limits:
        memory: "200Mi"
        cpu: "4"
    env:
    - name: tool
      value: "cyclictest"
    - name: DURATION
      value: "1h"
    # cyclictest should run with an RT Priority of 95 when testing for RAN DU
    - name: rt_priority
      value: "95"
    - name: INTERVAL
      value: "1000"
    - name: delay
      value: "0"
    - name: TRACE_THRESHOLD
      value: ""
      # TRACE_THRESHOLD requires privileged=true and debug volume
    # # Following setting not required in OCP4.6+
    # - name: DISABLE_CPU_BALANCE
    #   value: "y"
    #   # DISABLE_CPU_BALANCE requires privileged=true
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
      #- mountPath: /sys/kernel/debug
      #  name: debug
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  #- name: debug
  #  hostPath:
  #    path: /sys/kernel/debug
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""
  
