apiVersion: v1
kind: Pod
metadata:
  name: rteval
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: rteval
    image: quay.io/container-perf-tools/rteval
    imagePullPolicy: Always
    env:
    - name: tool
      value: "rteval"
    - name: TRACE_CMD
      value: "y"
    securityContext:
      privileged: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""