apiVersion: v1
kind: Pod
metadata:
  name: timerlat
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: rtla
    image: quay.io/container-perf-tools/rtla
    imagePullPolicy: Always
    resources:
      requests:
        memory: "200Mi"
        cpu: "16"
      limits:
        memory: "200Mi"
        cpu: "16"
    env:
    - name: GIT_URL
      value: "false"
    - name: tool
      value: "rtla"
    - name: COMMAND
      value: "timerlat"
    - name: DELAY
      value: "30"
    - name: DURATION
      value: "24h"
    - name: MAX_LATENCY
      value: "20"
    - name: EXTRA_ARGS
      value: "--dma-latency 0"
    securityContext:
      # Required for access to /dev/cpu_dma_latency and /sys/kernel/debug on the host
      privileged: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""
